name: odo-podman-test
on:
  pull_request:
    branches:    
      - main


jobs:

  odo-podman-test-v3:
    runs-on: ubuntu-22.04
    steps:

    - run: podman info

    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup Go
      uses: actions/setup-go@v3
      with:
        go-version-file: 'go.mod'

    - name: Build odo
      run: make install

    - name: Run Integration tests
      env:
        # This should ideally be a configuration in the GH repo (secret or variable).
        # This is currently hard-coded because GH won't expose secrets or variables to PRs created from forks.
        # Hopefully, variables (which are non-sensible by definition) will be passed to workflows triggered by PRs from forks.
        # See https://github.com/community/community/discussions/44322
        PODMAN_EXEC_NODES: 10
      run: make test-integration-podman

    - name: List and stop remaining containers
      if: ${{ always() }}
      run: |
        podman pod ls --format '{{.Name}}' | xargs -I '{}' podman pod inspect '{}'
        podman pod ls --format '{{.Name}}' | xargs podman pod stop || true

  odo-podman-test-latest:
    runs-on: ubuntu-latest
    steps:

    - name: Install latest podman
      run: |
        sudo apt-get update -y -qq
        sudo mkdir -p /etc/apt/keyrings
        curl -fsSL https://download.opensuse.org/repositories/devel:kubic:libcontainers:unstable/xUbuntu_$(lsb_release -rs)/Release.key \
          | gpg --dearmor \
          | sudo tee /etc/apt/keyrings/devel_kubic_libcontainers_unstable.gpg > /dev/null
        echo \
          "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/devel_kubic_libcontainers_unstable.gpg]\
            https://download.opensuse.org/repositories/devel:kubic:libcontainers:unstable/xUbuntu_$(lsb_release -rs)/ /" \
          | sudo tee /etc/apt/sources.list.d/devel:kubic:libcontainers:unstable.list > /dev/null
        sudo apt-get update -qq
        sudo apt-get -qq -y install podman

    - run: podman info

    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup Go
      uses: actions/setup-go@v3
      with:
        go-version-file: 'go.mod'

    - name: Build odo
      run: make install

    - name: Run Integration tests
      env:
        # This should ideally be a configuration in the GH repo (secret or variable).
        # This is currently hard-coded because GH won't expose secrets or variables to PRs created from forks.
        # Hopefully, variables (which are non-sensible by definition) will be passed to workflows triggered by PRs from forks.
        # See https://github.com/community/community/discussions/44322
        PODMAN_EXEC_NODES: 10
        PODMAN_USE_NAMESPACES: 'false'
      run: make test-integration-podman

    - name: List and stop remaining containers
      if: ${{ always() }}
      run: |
       podman pod ls --format '{{.Name}}' | xargs -I '{}' podman pod inspect '{}'
       podman pod ls --format '{{.Name}}' | xargs podman pod stop || true
